title: "Amogh Dwivedi | Portfolio"
description: "Personal portfolio showcasing my projects, skills, and achievements"
author: "Amogh Dwivedi"
email: "amogh.d.wrk@gmail.com"
url: "https://Amogh-Dwivedi.github.io"
baseurl: ""   # keep empty since this is a user site

# Optional: if you want RSS and SEO
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

lang: en
timezone: Asia/Kolkata
